import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { Marquee } from "./components/Marquee";
import { Toaster } from "sonner";
import { CartSheet } from "@/components/cart-sheet";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-right" theme="dark" />
        <CartSheet />
        <Marquee />
        <Navbar />
        <div className="relative z-10 bg-zinc-950 min-h-screen pb-20">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
